[package]
name = "parfait-gfa"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
owo-colors = "4"
paste = "1.0.15"
si-scale = "0.2.3"

[profile.profiling]
inherits = "release"
debug = true
